### ISSUE TITLE
Settingslogic::MissingSetting: Missing setting

### ISSUE THREAD

**Issue by kaiquealencar** [binarylogic/settingslogic#59]
Hi guys, I'm using settingslogic in my application, I did this configuration:
# config/application.yml

defaults: &defaults:
  mailchimp:
    api_key: 'here_my_mail_chimp_api_key '
    newsletter_id: 'here_my_news_letter_id'

production:
  <<: *defaults

development:
  <<: *defaults

But when I try to access by bash Settings.mailchimp, this happen
Settingslogic::MissingSetting: Missing setting

Someone knows what is this?
Thanks

**Comment by pixel-shock** [comment]
Hi,

why did you close this issue? Did you found a solution? I've got the same error :-(

``` yaml
defaults: &defaults
  myapp:
    host: localhost
    port: 80
    https: false
    email_from: support@myapp.com

production:
  <<: *defaults
  myapp:
    host: myapp.com
    port: 443
    https: true

development:
  <<: *defaults
  myapp:
    port: 3000

test:
  <<: *defaults
  myapp:
    port: 3000
```

If I try to access the "https" property in the "development" env, I get the "missing settings error" ...
