### ISSUE TITLE
stringify_keys returns whole config when used with a Hash value

### ISSUE THREAD

**Issue by ghost** [binarylogic/settingslogic#85]
I've a config which has one value as a Hash as follows:

```
PlannerConfig.driving
=> {"average_speed"=>50,
 "driver_off_duty_time"=>10,
 "max_driver_on_duty_time"=>14,
 "day_one_cap_value"=>300,
 "max_continuous_drive_time"=>10,
 "max_waiting_time"=>48,
 "mandatory_rest_after_drive"=>0.5,
 "sleeping_time"=>10}
```

`PlannerConfig` is using SettingsLogic to the values from a yaml file. The values are:

```
  distance:
    redis_cache: true
  ts:
    max_iterations: 1000
    max_unchanged_iterations: 200
    thread_count: 1
    timeout: 5
    shuffle: 5
    cost_tolerance: 1.0
    mode_selection: false
    cost_calculation: true
    ignore_capacity: false
  constraints:
    max_number_of_stops: 3
    out_of_route_items_attributes: [
      {distance_value: 0, percent: 40}
    ]
  driving:
    average_speed: 50
    driver_off_duty_time: 10
    max_driver_on_duty_time: 14
    day_one_cap_value: 300
    max_continuous_drive_time: 11
    max_waiting_time: 48
    mandatory_rest_after_drive: 0.5
    max_continuous_drive_time: 10
    sleeping_time: 10
  task:
    key: 'planner:running'
```

When passing this to an AR object as a parameter for initialization, it throws an error with missing attributes:

```
[1] pry(main)> Optimization::DrivingHoursConfiguration.new(PlannerConfig.driving)
ActiveRecord::UnknownAttributeError: unknown attribute 'distance' for Optimization::DrivingHoursConfiguration.
from /home/ashish/.rvm/gems/ruby-2.3.8/ruby/2.3.0/gems/activerecord-4.2.11/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
```

This happens in Rails 4.2.x, doesn't happen in Rails 4.1.x. On investigation I found out that when using `stringify_keys` the output is not as expected:

```
[2] pry(main)> PlannerConfig.driving
=> {"average_speed"=>50,
 "driver_off_duty_time"=>10,
 "max_driver_on_duty_time"=>14,
 "day_one_cap_value"=>300,
 "max_continuous_drive_time"=>10,
 "max_waiting_time"=>48,
 "mandatory_rest_after_drive"=>0.5,
 "sleeping_time"=>10}
[3] pry(main)> PlannerConfig.driving.stringify_keys
=> {"distance"=>{"redis_cache"=>true},
 "ts"=>{"max_iterations"=>2500, "max_unchanged_iterations"=>1000},
 "constraints"=>{"max_number_of_stops"=>3, "out_of_route_items_attributes"=>[{"distance_value"=>0, "percent"=>40}]},
 "driving"=>
  {"average_speed"=>50,
   "driver_off_duty_time"=>10,
   "max_driver_on_duty_time"=>14,
   "day_one_cap_value"=>300,
   "max_continuous_drive_time"=>10,
   "max_waiting_time"=>48,
   "mandatory_rest_after_drive"=>0.5,
   "sleeping_time"=>10},
 "task"=>{"key"=>"planner:running"},
 "average_speed"=>50,
 "driver_off_duty_time"=>10,
 "max_driver_on_duty_time"=>14,
 "day_one_cap_value"=>300,
 "max_continuous_drive_time"=>10,
 "max_waiting_time"=>48,
 "mandatory_rest_after_drive"=>0.5,
 "sleeping_time"=>10}
```

This is happening due to change in activesupport where we're using `self.class.new` instead of populating a hash, reference commit [here](https://github.com/rails/rails/commit/f1bad130d0c9bd77c94e43b696adca56c46a66aa#diff-91f6c0c36542ac9a44567631a533c501R10). So it does `PlannerConfig.new` which adds all the keys and hence getting this error.

For now I am doing `Optimization::DrivingHoursConfiguration.new(PlannerConfig.driving.to_h)`.
